### ISSUE TITLE
Add support for picture-based subtitles when enable_hdr_sdr_tonemapping is being used.

### ISSUE THREAD

**Issue by Collisionc** [Collisionc/sickbeard_mp4_automator#13]
Should be doable, found a guide on it here: https://stevens.li/guides/video/converting-hdr-to-sdr-with-ffmpeg/

**Comment by Collisionc** [comment]
After poking around, implementing this by itself is no problem, the difficulty will be making sure it works with resolution downscaling + subtitle burn-in with filter_complex being used rather than -vf. Should be doable, tho.

**Comment by weezzelboy** [comment]
any word on this enhancement. would love to have this add as my plex server is growing more and more to all HDR content.

**Comment by Collisionc** [comment]
I haven't had much free time to finish this, but it's definitely on my radar as the amount of HDR stuff increases and no one I know has a HDR tv/monitor. :D 

I'll try and get the bare-minimum implementation added over christmas... it won't work with burned in subtitles, but it'll be a start.

**Comment by Collisionc** [comment]
Ok, it should work with everything except picture-based subtitles. That's going to require one hell of a filter_complex line to pull off, and my head was starting to hurt when I looked into it.

**Comment by Collisionc** [comment]
Managed to get tonemap_opencl working locally... 18 fps vs 4 is a fairly significant jump.

**Comment by Collisionc** [comment]
added tonemap_opencl -- managed to get it up to 28 fps vs 4. 

https://github.com/Collisionc/sickbeard_mp4_automator/commit/d2f207ee4478373abff05f3e78b01dfd78837032
