### ISSUE TITLE
Feature REQ: Adding the Option for H265 / x265 with HDR encoding

### ISSUE THREAD

**Issue by weezzelboy** [Collisionc/sickbeard_mp4_automator#16]
Can you create an option to select x265/h265 encoding over x264 as files are growing in size do to 2160p and trueHD, x265 would reduce file size to over 50% thus reducing over all footprint on NAS or array considerably. and But adding the HDR10+ option you could encode with BT2020 colorspace and 10bit deepth. Which woould produce a small copy of a x265 10bit HDR copy.

-pix_fmt yuv420p10le 
-x265-params "colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc" 

here is a reference link to view..
https://superuser.com/questions/1280876/convert-youtube-hdr-vp9-2-video-to-hevc-hdr-with-ffmpeg

If i had the skills of a programmer i would attempt it, but i am lacking those skills..

Here is a Movie 12 Strong with HDR10+
MediaInfo Json format:

"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": "11832091923885050479",
"Format": "HEVC",
"Format_Commercial_IfAny": "HDR10",
"Format_Profile": "Main 10",
"Format_Level": "5.1",
"Format_Tier": "High",
"CodecID": "V_MPEGH/ISO/HEVC",
"Duration": "7839.375000000",
"BitRate": "46729958",
"Width": "3840",
"Height": "2160",
"Sampled_Width": "3840",
"Sampled_Height": "2160",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "24.000",
"FrameCount": "188145",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"ChromaSubsampling_Position": "Type 2",
"BitDepth": "10",
"Delay": "0.000",
"StreamSize": "45791708769",
"Default": "Yes",
"Forced": "No",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.2020",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "PQ",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.2020 non-constant",
"matrix_coefficients_Source": "Stream",
"MasteringDisplay_ColorPrimaries": "Display P3",
"MasteringDisplay_ColorPrimaries_Source": "Stream",
"MasteringDisplay_Luminance": "min: 0.0050 cd/m2, max: 1000 cd/m2",
"MasteringDisplay_Luminance_Source": "Stream",
"MaxCLL": "764 cd/m2",
"MaxCLL_Source": "Stream",
"MaxFALL": "374 cd/m2",
"MaxFALL_Source": "Stream"

Thanks weezzelboy

**Comment by weezzelboy** [comment]
So after alot o googling, i have found that by adding this to the "postopts= " section it is doable to carry over the metadata from a HDR mkv file to HDR mp4 file.
autoProcess.ini
`postopts = -preset,fast,-x265 -params,level=5.2:colorprim=bt2020:colormatrix=bt2020nc:transfer=smpte2084`

**Comment by Collisionc** [comment]
Closing as this should be taken care of upstream (ex, the issue you opened on mdhiggins)
