### ISSUE TITLE
Subliminal v2 upgrade?

### ISSUE THREAD

**Issue by uchagani** [Collisionc/sickbeard_mp4_automator#19]
Wondering if you know what it would take to upgrade to subliminal v2?  I'm willing to help out where I can.

**Comment by Collisionc** [comment]
Sorry for the super late response, I do not know what it would take... I've barely looked at the subliminal code. I'll check it out sometime in the next few weeks.

**Comment by Collisionc** [comment]
Closing issue, I'm going to rebase my fork on changes from mdhiggins, I think this was implemented in his....
