### ISSUE TITLE
"burn_in_forced_subs = True" not working as expected

### ISSUE THREAD

**Issue by Smalfinn** [Collisionc/sickbeard_mp4_automator#20]
I'm trying to burn in the signs and songs subtitle track for an anime, the subs are marked as forced but they're not being burned in

Is it because the file has an eng audio track and a jpn track?

[MP4]: https://pastebin.com/raw/jXxX2TXv
index.log: https://pastebin.com/raw/SWTdN1Qc

anime mkv mediainfo: https://pastebin.com/raw/rEM9mLvk

**Comment by Collisionc** [comment]
Yeah, that is a scenario that I did not test out... I'll check it out. Thanks for reporting.

**Comment by Collisionc** [comment]
Ok, I see what's going on. It's due to embed-subs = False in your autoprocess.ini. I think I copy/pasted a line or 2 from somewhere else in the code and it had a check for embedsubs in it, even though that's not useful for this particular case. 

I'll fix it in the code so it doesn't matter, but temporarily if you set embed-subs = True in your autoprocess.ini it should work.

**Comment by Smalfinn** [comment]
I'll try it out today :)

Thank you

**Comment by Smalfinn** [comment]
Script threw an error. Will I also have to define mov_text for my subtitle format too

mediaInfo : https://pastebin.com/raw/wpzcVXZv
index.log : https://pastebin.com/raw/h1d83htE

**Comment by Collisionc** [comment]
Yeah, you may have to define mov_text, can you post the [MP4] section of your autoprocess.ini ? Just so I can reproduce what you're seeing.

**Comment by Smalfinn** [comment]
Script was not a fan of mov_text either

index.log : https://pastebin.com/raw/H4ZFA4Kr

**Comment by Collisionc** [comment]
Remove the UTF-8 encoding from subtitle-encoding
subtitle-encoding =
I've never used that option, so I'm not sure what it could be used for, but clearing that should allow it to run.

**Comment by Smalfinn** [comment]
It was to ensure the subs were formatted correctly

Another error
index.log : https://pastebin.com/raw/ZzmN01HU
[MP4] : https://pastebin.com/raw/Eaxcnsqi

**Comment by Collisionc** [comment]
Ah, it's the [] characters in the filename... I'll have to add more backslashes in the code. Rename the file to something like test.mkv and see if it runs. You might be able to place UTF-8 back in as well.

**Comment by Smalfinn** [comment]
I removed the [] brackets from the titles of everything and still got an error.

index.log : https://pastebin.com/raw/nTYhupD9

**Comment by Collisionc** [comment]
Bleh, it's erroring out on the subtitle-encoding = UTF-8 again, so remove it once more. I'll fix that stuff eventually, just trying to find all the options that are causing issues before I get into it.

**Comment by Smalfinn** [comment]
Removed subtitle-encoding = UTF-8 but another error.

index.log : https://pastebin.com/raw/95WZqSbc

**Comment by Collisionc** [comment]
Try renaming file to test.mkv and see if it goes through, I'll work on fixing the issues with certain punctuation.

**Comment by Smalfinn** [comment]
Renamed to test.mkv

Tested with embed-subs = False, burn_in_forced_subs = False, just to see if the script worked still, it did
index.log : https://pastebin.com/raw/XcZ69Qj0

Then tested with:
[MP4] : https://pastebin.com/raw/apDGAhkw
index.log : https://pastebin.com/raw/CRjRxiSb
Burned in the forced sub track but then deleted the other instead of re-embedding it as a mov_text
