### ISSUE TITLE
[Question] keeping hdr

### ISSUE THREAD

**Issue by nexus671** [Collisionc/sickbeard_mp4_automator#21]
How do you maintain hdr for video that has it? I tried these settings and wont run be because of -x265 param. 

Trying to do this with nvenc_h265 so i can utilize GPU (rtx 2080).

```
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mkv
output_format = mkv
delete_original = True
relocate_moov = True
video-codec = nvenc_h265
video-bitrate = 60000
resolution-bitrate-restriction = 
video-crf = 17
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
qmin = 
qmax = 
global_quality = 
maxrate = 
minrate = 
bufsize = 
nvenc_encoder_gpu =
nvenc_profile = 
nvenc_preset = slow
nvenc_rate_control = vbr_hq
nvenc_temporal_aq = True
nvenc_weighted_prediction = False
nvenc_rc_lookahead = 
enable_nvenc_decoder = False
enable_nvenc_hevc_decoder = False
nvenc_decoder_gpu =
nvenc_hevc_decoder_gpu = 
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 6
audio-codec = aac
ignore-truehd = true
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = srt 
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = nv12, yuv420p
aac_adtstoasc = False
handle_m2ts_files = False
forceconvert = False
vsync = -1
sample_rate = 
burn_in_forced_subs = False
burn_in_full_subs = False
enable_hdr_sdr_tonemapping = False
enable_opencl_hdr_sdr_tonemapping = False
init_hw_device = opencl=gpu:0
preopts = 
postopts = -x265 -params,colorprim=bt2020:colormatrix=bt2020nc:transfer=smpte2084
```

**Comment by Collisionc** [comment]
Hrm. Good question, shot in the dark guess - try dropping -x265 from the postops (Leave the -params) and add yuv444p16le (or p0161e) to the pix-fmt list. I'd recommend having a backup of the media file or setting delete_original = False until you test it a few times. 

I'll look through ffmpeg/nvidia docs to see if there's a recommended way of doing this. I remember reading somewhere that it wasn't possible to transfer HDR metadata over NVENC, but this was probably a year ago and may have been resolved by now.

**Comment by nexus671** [comment]
thank ill try that out. If it doesn't work any other recommendations? How else would i utilize my GPU and maintain hdr with x265.

**Comment by weezzelboy** [comment]
this is what i use for all my HDR content... But they are remuxed into x265 NEVC from mostly x264 

[MP4]
ffmpeg = C:\ffmpeg\bin-video\ffmpeg.exe
ffprobe = C:\ffmpeg\bin-video\ffprobe.exe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = nvenc_h265,x265,hevc,h265,HEVC,h.265
video-bitrate = 
resolution-bitrate-restriction = 
video-crf = 22
video-max-width = 
video-profile = main10
h264-max-level = 5.1
use-qsv-decoder-with-encoder = false
use-hevc-qsv-decoder = false
enable_dxva2_gpu_decode = false
ios-audio = false
qmin = 
qmax = 
global_quality = 
maxrate = 
minrate = 
bufsize = 
nvenc_encoder_gpu = 0
nvenc_profile = main10
nvenc_preset = faster
nvenc_rate_control = vbr_hq
nvenc_temporal_aq = true
nvenc_weighted_prediction = true
nvenc_rc_lookahead =0
enable_nvenc_decoder = true
enable_nvenc_hevc_decoder = true
nvenc_decoder_gpu = 0
nvenc_hevc_decoder_gpu = 0
ios-first-track-only = True
ios-audio-filter = volume=2
ios-move-last = True
max-audio-channels = 
audio-codec = ac3,eac3,dts,dca,aac
ignore-truehd = true
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 192
audio-filter = volume=2
audio-copy-original = false
audio-first-track-of-language = True
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = false
tag-language = en
download-artwork = Poster
download-subs = true
embed-subs = True
embed-only-internal-subs = True
sub-providers = podnapisi,addic7ed,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = yuv420p10le
aac_adtstoasc = false
handle_m2ts_files = false
forceconvert = False
vsync = -1
sample_rate = 48000
burn_in_forced_subs = false
postopts = -x265-params, colorprim=bt2020:colormatrix=bt2020nc:transfer=smpte2084
preopts = -loglevel,debug,-probesize,50000,-analyzeduration,100000m
enable_hdr_sdr_tonemapping = False
enable_opencl_hdr_sdr_tonemapping = false
init_hw_device = opencl=gpu:0
burn_in_full_subs = false
