### ISSUE TITLE
NZBget Progress

### ISSUE THREAD

**Issue by justinglock40** [Collisionc/sickbeard_mp4_automator#3]
Are you able to add something to NZBget that outputs the progress?

<img width="1630" alt="screenshot at oct 01 18-32-04" src="https://user-images.githubusercontent.com/23133649/31060307-04015836-a6d7-11e7-8d0b-0020e226bbbf.png">

**Comment by Collisionc** [comment]
I don't think NZBget allows scripts to modify the progress bar. 

I could have it log the % complete every minute, so it would say "30% done" instead of "Output file blah blah blah".

**Comment by justinglock40** [comment]
That’s cool. I though maybe it would be possible because when the file unraring it shows the program progress as well as the time left to complete.

**Comment by Collisionc** [comment]
Yeah, but that's part of NZBGet, it does that without additional scripts.

**Comment by justinglock40** [comment]
That is true maybe he built it into the program. Because I was looking and it actually offers the ability to change the between unrar or 7zip applications by just pointing to the .exe in the cause of windows, but that isn’t really a necessity just thought I’d ask. Thanks for looking into it though. One question I did have was about the Deluge thing. Do you think that is a possibility?

**Comment by Collisionc** [comment]
Yeah, smarter skipping of sample files should be doable for deluge, I'll check what nzbget does to detect sample files and see if I can add it into this.
