### ISSUE TITLE
keep x265/hevc

### ISSUE THREAD

**Issue by davidpearce** [Collisionc/sickbeard_mp4_automator#6]
Hey Collisionc,
Is there a way to keep the output format as hevc?
I just want the mp4 remux and tagging, I don't need everything stored as x264.

Thanks

**Comment by justinglock40** [comment]
make your video-codec line look like this to copy all video streams: 
video-codec = h264,x264,h.264,nvenc_h265,hevc,h265,x265,HEVC,h.265

You can take out the nvenc if you're not going to ever convert using GPU

**Comment by davidpearce** [comment]
Thanks I’ll give it a try 😄
